#!/bin/bash

set -e

MEMORY_ALPHA_S3_BUCKET=
S3_KEY=wal/$2.bz2
S3_DEST=s3://${MEMORY_ALPHA_S3_BUCKET}/${S3_KEY}

aws s3api head-object --bucket ${MEMORY_ALPHA_S3_BUCKET} --key ${S3_KEY} > /dev/null 2>&1
status=$?

if [ $status = 0 ]; then
	echo "key ${S3_KEY} exists already."
	exit 2
fi

bzip2 -c -9 $1 > /tmp/$2.bz2
aws s3 cp --sse aws:kms /tmp/$2.bz2 ${S3_DEST}
rm -f /tmp/$2.bz2